people/zivKalderon.json
Adding myself...
Really cool project:)
=> Ziv Kalderon

people/ronfybish.json
Good luck my dear friends (:
Great project I really liked the idea 💯
=> Create a community member ronfybish.json file

package-lock.json, package.json
=> chore(deps): next v10.0.0

people/ealush.json
=> feat: add ealush ✌️

people/yanaiedri.json
=> adding my info

pages/index.tsx, people/naorpeled.json, styles/Home.module.css
- Added naorpeled.json
- Separated the information into sections
- Added an about section
- The 'join us' section now contains an underlined link instead of a button while maintaining the page's overall design pattern
=> Add myself and adjust the layout a bit

people/YoniMelki.json
Added User Yoni Melki to the people directory
=> Yoni Melki

people/guysoft.json
=> Add GuySoft

components/showMore/showMore.tsx, people/lurx.json
=> Rotem horovitz

people/avivnakar.json
I just wanted to be as cool as @ealush so here is a screenshot:
=> feat: add avivnakar

people/SaharHagbi.json
Hi:)
my name is sahar hagbi and this is my profile
=> adding profile

people/soferdani.json
=> add me to people

components/socialNetworks/socialNetworks.tsx
=> Update Discord link

people/yuvalabou.json
Add myself to the pull request community
=> Add Yuval Aboulafia :sparkles:

styles/Home.module.scss
changed the minimum width of the cards from 350px to 250px
=> changing min size cards

people/yonbav.json
=> adding yonbav profile

people/TomerFi.json
Hey
Cool project, thank you for sharing.
I added myself to the pepole folder.
Have a great day.
=> Added TomerFi profile

components/description/description.module.scss
Enabled the  hand icon's link from `MainPageDescription`
=> fix: disabled link

package.json
Hi @MichalPorag , didnt changed the `npm start` script as its a nextjs script for running on production
instead, i added to the `dev` script a script that opens the localhost.
=> #157|Resolved|open local host when running dev script

components/description/Description.tsx, components/description/description.module.scss, components/layout/navbar/navbar.module.scss, components/layout/navbar/navbar.tsx, components/projectPage/ProjectPage.module.scss, components/socialNetworks/socialNetworks.module.scss, styles/globals.scss
close #159 
Should we change the font size of the names in the cards now?
=> fix style according to Figma

people/OmriBarZik.json, people/omribarzik.json
=> feat: add Omri Bar-Zik profile

pages/api/hello.ts
Remove the file `pages/api/hello.ts`
This file has no use in the project and we don't intend to have `api/hello.ts` page
Closes  #172
=> chore: remove unnecesaary file

package.json
* delete `git add` in `package.json`
* fix ` people/*.json` path
close #193
=> fix: lint stage config

.husky/pre-commit, package-lock.json, package.json
* Upgrade husky from version 4 to version 8
* lockfileVersion updated to version 2
close #191 
close #187
=> build: upgrade husky

package.json, scripts/open-browser.js
Fix `npm run dev`,
Now opening localhost on every major operating system
close #157
=> fix: open localhost

README.md
Following issue #78, update readme accordingly
=> fix: Readme - add custom image explanation

.github/workflows/e2e-ci.yml, e2e/home.spec.ts, package-lock.json, package.json, playwright.config.ts
Adding infrastructure for running end-to-end test suite
=> test: add e2e infra with playwright and a sample test

.editorconfig, prettier.config.js
updated editor config  and prettier configs to be aligned
=> build: align editorconfig & prettier configs

components/buttons/basicButton.tsx, components/buttons/socialButton.tsx, components/description/description.module.scss, components/layout/navbar/navbar.tsx, components/personCard/personCard.module.scss, components/projectPage/ProjectPage.module.scss, components/typography/title.tsx, styles/globals.scss, styles/typography.scss
@MichalPorag please review my PR
=> Typograpy styles

people/YonatanBenEzra.json
Delete old accounts that throw the error ` failed to load resource`
=> fix: failed to load resource

people/EladMotzny.json
Hi!
Added a PR with my info in it. Thanks!
=> Added a new profile

docs/contributing.md
=> Fixed typos

components/layout/navbar/navbar.module.scss, components/layout/navbar/navbar.tsx
=> Remove style tag from components and refactor the code accordingly

.github/workflows/e2e-ci.yml, package-lock.json, package.json
* Fixed e2e tests job
@MichalPorag @lirantal @abrl91 
Eslint + json by #290
=> ci: fix e2e tests by updating Playwright
